/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        NodeHandler handler = new App().parseJson();
        if(handler == null) {
            System.out.print("error");
        } else {
            System.out.print(handler.toString());
        }
    }

    NodeHandler parseJson() {
        try {
            return Json.readJson();
        } catch (Exception ex) {
            System.out.println("Exception in json parser: " + ex.getMessage() + ". Cause: " + ex.getCause());
        }
        return null;
    }
}
